### PR TITLE
added

### PR DESCRIPTION
**Pull request by SAKETSINGH120**
issue no. #7 
solved
hey @bobbyy16 please merge

### CODE REVIEW

**Comment by bobbyy16** [comment]
Hey @SAKETSINGH120 thanks for the contribution but can you make region-specific, Instead of global, Can you just go Indian region like "Banglore, Karnataka"

**Comment by SAKETSINGH120** [comment]
But no specific location

**Comment by bobbyy16** [comment]
No, This website is about companies in India. What I want you to do is just mention the location of there main office in India

**Comment by SAKETSINGH120** [comment]
Ok

**Comment by bobbyy16** [comment]
Can you just make changes and commit @SAKETSINGH120

**Pull request merged**
