### PR TITLE
new Company Added

### PR DESCRIPTION
**Pull request by SAKETSINGH120**
new Company Details Added
hey @bobbyy16  please merge
Screenshot (78)

### CODE REVIEW

**Comment by bobbyy16** [comment]
Hey @SAKETSINGH120 , thanks for your contribution. Can you change Mysuru, Mumbai to Mumbai, Maharastra

**Comment by bobbyy16** [comment]
Also Mention the issue number while creating pull request

**Comment by SAKETSINGH120** [comment]
ok

**Comment by bobbyy16** [comment]
@SAKETSINGH120 , TCS doesn't have an office in Mysuru, can you remove Mysuru and add only Mumbai, Maharastra

**Comment by bobbyy16** [comment]
Can you kindly do the changes, so that I can merge your PR.

**Comment by bobbyy16** [comment]
Reopen the PR, please.

**Comment by SAKETSINGH120** [comment]
ok thanks for understanding my mistake and then correcting it

**Comment by bobbyy16** [comment]
no issues, add more companies. if you anything in your mind

**Pull request merged**
